version: '3.5'

services:
  d3-iroha:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: d3-iroha
    depends_on:
      - d3-iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    volumes:
      - iroha_block_store:/tmp/block_store
      - ./deploy/iroha/:/opt/iroha_data
    networks:
      - d3-network

  d3-iroha-postgres:
    image: postgres:9.5
    container_name: d3-iroha-postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - /var/lib/postgresql/data
    networks:
      - d3-network

  d3-rmq:
    image: rabbitmq:3-management
    container_name: d3-rmq
    ports:
      - 8181:15672
      - 5672:5672
    networks:
      - d3-network

  d3-chain-adapter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ARGS= -x integrationTest
    container_name: d3-chain-adapter
    restart: on-failure
    depends_on:
      - d3-iroha
      - d3-rmq
    links:
      - d3-iroha
      - d3-rmq
    volumes:
      - ../deploy/chain-adapter/:/opt/chain-adapter/deploy/chain-adapter
      - ../deploy/iroha/keys:/opt/chain-adapter/deploy/iroha/keys
    environment:
      - WAIT_HOSTS=d3-iroha:50051, d3-rmq:5672
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
      - PROFILE
      - IROHA_HOST=d3-iroha
      - IROHA_PORT=50051
    networks:
      - d3-network
volumes:
  iroha_block_store:

networks:
  d3-network:
